---
kolla-build:
  DEFAULT:
    base: rocky
    base_image: quay.io/rockylinux/rockylinux
    base_tag: 9
    cache: true
    engine: docker
    maintainer: Tadas Sutkaitis <tadasas@gmail.com>
    namespace: fitbeard/kolla
    pull: true
    registry: quay.io
    tag: '2023.2'
  cinder-base:
    location: https://github.com/openstack/cinder.git
    reference: 9e667b02b2c20b4ada18c1a472be152956284d45
    type: git
  glance-base:
    location: https://github.com/openstack/glance.git
    reference: 8540ffc6ee34976285209e9f3c7c728bf649e0ff
    type: git
  heat-base:
    location: https://github.com/openstack/heat.git
    reference: 39eca5de2e193f652792e4f7be2e5eb96dd3d853
    type: git
  horizon:
    location: https://github.com/openstack/horizon.git
    reference: 6f0e86358011f9a59ef69e7d459a40c809c53e2f
    type: git
  horizon-plugin-blazar-dashboard:
    enabled: false
  horizon-plugin-cloudkitty-dashboard:
    enabled: false
  horizon-plugin-designate-dashboard:
    enabled: false
  horizon-plugin-freezer-web-ui:
    enabled: false
  horizon-plugin-heat-dashboard:
    enabled: false
  horizon-plugin-ironic-ui:
    enabled: false
  horizon-plugin-magnum-ui:
    enabled: false
  horizon-plugin-manila-ui:
    enabled: false
  horizon-plugin-masakari-dashboard:
    enabled: false
  horizon-plugin-mistral-dashboard:
    enabled: false
  horizon-plugin-murano-dashboard:
    enabled: false
  horizon-plugin-neutron-vpnaas-dashboard:
    enabled: false
  horizon-plugin-octavia-dashboard:
    enabled: false
  horizon-plugin-sahara-dashboard:
    enabled: false
  horizon-plugin-senlin-dashboard:
    enabled: false
  horizon-plugin-solum-dashboard:
    enabled: false
  horizon-plugin-tacker-dashboard:
    enabled: false
  horizon-plugin-trove-dashboard:
    enabled: false
  horizon-plugin-venus-dashboard:
    enabled: false
  horizon-plugin-vitrage-dashboard:
    enabled: false
  horizon-plugin-watcher-dashboard:
    enabled: false
  horizon-plugin-zun-ui:
    enabled: false
  keystone-base:
    location: https://github.com/openstack/keystone.git
    reference: fee954e9b48fa7a57bdf3ef98e50f743fda969f5
    type: git
  neutron-base:
    location: https://github.com/openstack/neutron.git
    reference: 40e7e1ec921c4146f007d8d810b08128fb28fcd2
    type: git
  neutron-base-plugin-networking-baremetal:
    enabled: false
  neutron-base-plugin-networking-generic-switch:
    enabled: false
  neutron-base-plugin-networking-sfc:
    enabled: false
  neutron-base-plugin-vpnaas-agent:
    enabled: false
  nova-base:
    location: https://github.com/openstack/nova.git
    reference: 2856e943442d2706331ac175f29199d5f220a935
    type: git
  nova-base-plugin-blazar:
    enabled: false
  openstack-base:
    location: https://github.com/openstack/requirements.git
    reference: 54471ef8753b4f9f270f1b5a45f7e82597d62ff5
    type: git
  placement-base:
    location: https://github.com/openstack/placement.git
    reference: a361622d749d3b24aad638ec1b03a7d7124a87b3
    type: git
  profiles:
    cinder: cinder
    heat: heat
    horizon: horizon
    main: >-
      cron,cinder,kolla-toolbox,fluentd,glance,haproxy,heat,
      horizon,keepalived,keystone,mariadb,memcached,neutron,
      nova-,placement,openvswitch,ovn,rabbitmq,rsyslog
    mariadb: mariadb
    mcrouter: mcrouter
    neutron: neutron
    nova: nova-
    toolbox: kolla-toolbox
  skyline-apiserver:
    location: https://github.com/openstack/skyline-apiserver.git
    reference: 326a503d6cece6701922a5a3ed1a980efa12e2f5
    type: git
  skyline-console:
    location: https://github.com/openstack/skyline-console.git
    reference: d4cae6dd6a96d74b754c590fd2dd48fab83a345f
    type: git
sources:
  branch: stable/2023.2
  owner: openstack
  repository:
    cinder:
      kolla:
        - cinder-base
    glance:
      kolla:
        - glance-base
    heat:
      kolla:
        - heat-base
    horizon:
      kolla:
        - horizon
    keystone:
      kolla:
        - keystone-base
    neutron:
      kolla:
        - neutron-base
    nova:
      kolla:
        - nova-base
    placement:
      kolla:
        - placement-base
    requirements:
      kolla:
        - openstack-base
