---
kolla-build:
  DEFAULT:
    base: rocky
    base_image: quay.io/rockylinux/rockylinux
    base_tag: 9
    cache: true
    engine: docker
    maintainer: Tadas Sutkaitis <tadasas@gmail.com>
    namespace: fitbeard/kolla
    pull: true
    registry: quay.io
    tag: '2023.2'
  cinder-base:
    location: https://github.com/openstack/cinder.git
    reference: 79197560b6d68d80a504e74ee66caa44e2808158
    type: git
  glance-base:
    location: https://github.com/openstack/glance.git
    reference: 5b4be5b6f2f67ec8e61bceff8c2ed79b870aace0
    type: git
  heat-base:
    location: https://github.com/openstack/heat.git
    reference: 4fd9953a55c15e1d6d0bfb8f648d03d9e368fc3b
    type: git
  horizon:
    location: https://github.com/openstack/horizon.git
    reference: 6f0e86358011f9a59ef69e7d459a40c809c53e2f
    type: git
  horizon-plugin-blazar-dashboard:
    enabled: false
  horizon-plugin-cloudkitty-dashboard:
    enabled: false
  horizon-plugin-designate-dashboard:
    enabled: false
  horizon-plugin-freezer-web-ui:
    enabled: false
  horizon-plugin-heat-dashboard:
    enabled: false
  horizon-plugin-ironic-ui:
    enabled: false
  horizon-plugin-magnum-ui:
    enabled: false
  horizon-plugin-manila-ui:
    enabled: false
  horizon-plugin-masakari-dashboard:
    enabled: false
  horizon-plugin-mistral-dashboard:
    enabled: false
  horizon-plugin-murano-dashboard:
    enabled: false
  horizon-plugin-neutron-vpnaas-dashboard:
    enabled: false
  horizon-plugin-octavia-dashboard:
    enabled: false
  horizon-plugin-sahara-dashboard:
    enabled: false
  horizon-plugin-senlin-dashboard:
    enabled: false
  horizon-plugin-solum-dashboard:
    enabled: false
  horizon-plugin-tacker-dashboard:
    enabled: false
  horizon-plugin-trove-dashboard:
    enabled: false
  horizon-plugin-venus-dashboard:
    enabled: false
  horizon-plugin-vitrage-dashboard:
    enabled: false
  horizon-plugin-watcher-dashboard:
    enabled: false
  horizon-plugin-zun-ui:
    enabled: false
  keystone-base:
    location: https://github.com/openstack/keystone.git
    reference: 1829ce0202cbe11602fafd053cd1cd3eb0f996b0
    type: git
  neutron-base:
    location: https://github.com/openstack/neutron.git
    reference: c06cc4462b4b5c9270f94db951533db8da9079da
    type: git
  neutron-base-plugin-networking-baremetal:
    enabled: false
  neutron-base-plugin-networking-generic-switch:
    enabled: false
  neutron-base-plugin-networking-sfc:
    enabled: false
  neutron-base-plugin-vpnaas-agent:
    enabled: false
  nova-base:
    location: https://github.com/openstack/nova.git
    reference: be987f5481bdd1f616f32a919bb7a64a643109f0
    type: git
  nova-base-plugin-blazar:
    enabled: false
  openstack-base:
    location: https://github.com/openstack/requirements.git
    reference: f18d00dc711735bdd98d985513e4a3edec44dd04
    type: git
  placement-base:
    location: https://github.com/openstack/placement.git
    reference: a361622d749d3b24aad638ec1b03a7d7124a87b3
    type: git
  profiles:
    cinder: cinder
    heat: heat
    horizon: horizon
    main: >-
      cron,cinder,kolla-toolbox,fluentd,glance,haproxy,heat,
      horizon,keepalived,keystone,mariadb,memcached,neutron,
      nova-,placement,openvswitch,ovn,rabbitmq,rsyslog
    mariadb: mariadb
    mcrouter: mcrouter
    neutron: neutron
    nova: nova-
    toolbox: kolla-toolbox
  skyline-apiserver:
    location: https://github.com/openstack/skyline-apiserver.git
    reference: 326a503d6cece6701922a5a3ed1a980efa12e2f5
    type: git
  skyline-console:
    location: https://github.com/openstack/skyline-console.git
    reference: d4cae6dd6a96d74b754c590fd2dd48fab83a345f
    type: git
sources:
  branch: stable/2023.2
  owner: openstack
  repository:
    cinder:
      kolla:
        - cinder-base
    glance:
      kolla:
        - glance-base
    heat:
      kolla:
        - heat-base
    horizon:
      kolla:
        - horizon
    keystone:
      kolla:
        - keystone-base
    neutron:
      kolla:
        - neutron-base
    nova:
      kolla:
        - nova-base
    placement:
      kolla:
        - placement-base
    requirements:
      kolla:
        - openstack-base
