---
kolla-build:
  DEFAULT:
    base: rocky
    base_image: quay.io/rockylinux/rockylinux
    base_tag: 9
    cache: true
    engine: docker
    maintainer: Tadas Sutkaitis <tadasas@gmail.com>
    namespace: fitbeard/kolla
    pull: true
    registry: quay.io
    tag: '2024.1'
  cinder-base:
    location: https://github.com/openstack/cinder.git
    reference: a54442aef0860876db85b29f8df1b2c1245aecd9
    type: git
  glance-base:
    location: https://github.com/openstack/glance.git
    reference: 265ad47616f1ef8d762448705a0637931e04c33a
    type: git
  heat-base:
    location: https://github.com/openstack/heat.git
    reference: 435f17f855900af1010223aad0c3c8f585957f41
    type: git
  horizon:
    location: https://github.com/openstack/horizon.git
    reference: b06ce1c2a1baa6bd53e70f407cd2194aadcf169e
    type: git
  horizon-plugin-blazar-dashboard:
    enabled: false
  horizon-plugin-cloudkitty-dashboard:
    enabled: false
  horizon-plugin-designate-dashboard:
    enabled: false
  horizon-plugin-fwaas-dashboard:
    enabled: false
  horizon-plugin-heat-dashboard:
    enabled: false
  horizon-plugin-ironic-ui:
    enabled: false
  horizon-plugin-magnum-ui:
    enabled: false
  horizon-plugin-manila-ui:
    enabled: false
  horizon-plugin-masakari-dashboard:
    enabled: false
  horizon-plugin-mistral-dashboard:
    enabled: false
  horizon-plugin-neutron-vpnaas-dashboard:
    enabled: false
  horizon-plugin-octavia-dashboard:
    enabled: false
  horizon-plugin-tacker-dashboard:
    enabled: false
  horizon-plugin-trove-dashboard:
    enabled: false
  horizon-plugin-venus-dashboard:
    enabled: false
  horizon-plugin-watcher-dashboard:
    enabled: false
  horizon-plugin-zun-ui:
    enabled: false
  keystone-base:
    location: https://github.com/openstack/keystone.git
    reference: 2db5df14db2732ababef511495f695deadcbe310
    type: git
  neutron-base:
    location: https://github.com/openstack/neutron.git
    reference: 5958e01ce83e3f796cb0be28cfdd44a25521b77f
    type: git
  neutron-base-plugin-networking-baremetal:
    enabled: false
  neutron-base-plugin-networking-generic-switch:
    enabled: false
  neutron-base-plugin-networking-sfc:
    enabled: false
  neutron-base-plugin-neutron-fwaas:
    enabled: false
  neutron-base-plugin-vpnaas-agent:
    enabled: false
  nova-base:
    location: https://github.com/openstack/nova.git
    reference: fea4c102269bb9cea1f644c632e8c56267bbb10c
    type: git
  nova-base-plugin-blazar:
    enabled: false
  placement-base:
    location: https://github.com/openstack/placement.git
    reference: af00c864e98ae76cae3e621ad95868234d027882
    type: git
  profiles:
    cinder: cinder
    heat: heat
    horizon: horizon
    main: >-
      cron,cinder,kolla-toolbox,fluentd,glance,haproxy,heat,
      horizon,keepalived,keystone,mariadb,memcached,neutron,
      nova-,placement,openvswitch,ovn,rabbitmq,rsyslog
    mariadb: mariadb
    mcrouter: mcrouter
    neutron: neutron
    nova: nova-
    toolbox: kolla-toolbox
  skyline-apiserver:
    location: https://github.com/openstack/skyline-apiserver.git
    reference: 326a503d6cece6701922a5a3ed1a980efa12e2f5
    type: git
  skyline-console:
    location: https://github.com/openstack/skyline-console.git
    reference: d4cae6dd6a96d74b754c590fd2dd48fab83a345f
    type: git
sources:
  branch: stable/2024.1
  owner: openstack
  repository:
    cinder:
      kolla:
        - cinder-base
    glance:
      kolla:
        - glance-base
    heat:
      kolla:
        - heat-base
    horizon:
      kolla:
        - horizon
    keystone:
      kolla:
        - keystone-base
    neutron:
      kolla:
        - neutron-base
    nova:
      kolla:
        - nova-base
    placement:
      kolla:
        - placement-base
