---
extends: default

rules:
  line-length:
    ignore: |
      .github/*.yaml
      .github/*.yml
      .github/workflows/*.yaml
      .github/workflows/*.yml
  truthy:
    ignore: |
      .github/*.yaml
      .github/*.yml
      .github/workflows/*.yaml
      .github/workflows/*.yml
