extends: default

rules:
  document-start:
    ignore: |
      .github/*.yaml
      .markdownlint.yaml
      .pre-commit-config.yaml
        document-start:
  truthy:
    ignore: |
      .github/*.yaml
