---
kolla-build:
  DEFAULT:
    base: rocky
    base_image: quay.io/rockylinux/rockylinux
    base_tag: 9
    cache: true
    maintainer: Tadas Sutkaitis <tadasas@gmail.com>
    namespace: fitbeard/kolla
    pull: true
    registry: quay.io
    tag: yoga-dev
  cinder-base:
    location: https://github.com/openstack/cinder.git
    reference: 752c9eacce42056522ce86febd29aa25c2fd91bd
    type: git
  example-with-owner-and-branch:
    location: https://github.com/fitbeard/awx-without-k8s.git
    reference: fa2ae3180f955612bc699471363694bb6b87bd99
    type: git
  glance-base:
    location: https://github.com/openstack/glance.git
    reference: 357e5ba1bb3a3a28baf844db698d1bfeff7593c1
    type: git
  heat-base:
    location: https://github.com/openstack/heat.git
    reference: 41a6b91362c3cf90bd3692c88b9840d6b1a8d56b
    type: git
  horizon:
    location: https://github.com/openstack/horizon.git
    reference: eb57aa5300be01a349684a8aa07d9a973357cf7d
    type: git
  horizon-plugin-blazar-dashboard:
    enabled: false
  horizon-plugin-cloudkitty-dashboard:
    enabled: false
  horizon-plugin-designate-dashboard:
    enabled: false
  horizon-plugin-freezer-web-ui:
    enabled: false
  horizon-plugin-heat-dashboard:
    enabled: false
  horizon-plugin-ironic-ui:
    enabled: false
  horizon-plugin-magnum-ui:
    enabled: false
  horizon-plugin-manila-ui:
    enabled: false
  horizon-plugin-masakari-dashboard:
    enabled: false
  horizon-plugin-mistral-dashboard:
    enabled: false
  horizon-plugin-monasca-ui:
    enabled: false
  horizon-plugin-murano-dashboard:
    enabled: false
  horizon-plugin-neutron-vpnaas-dashboard:
    enabled: false
  horizon-plugin-octavia-dashboard:
    enabled: false
  horizon-plugin-sahara-dashboard:
    enabled: false
  horizon-plugin-senlin-dashboard:
    enabled: false
  horizon-plugin-solum-dashboard:
    enabled: false
  horizon-plugin-tacker-dashboard:
    enabled: false
  horizon-plugin-trove-dashboard:
    enabled: false
  horizon-plugin-vitrage-dashboard:
    enabled: false
  horizon-plugin-watcher-dashboard:
    enabled: false
  horizon-plugin-zun-ui:
    enabled: false
  keystone-base:
    location: https://github.com/openstack/keystone.git
    reference: 7852ca24a4eb86cb271ef7ec5e07f8f9c97f926d
    type: git
  neutron-base:
    location: https://github.com/openstack/neutron.git
    reference: f5523b2977bb68478c70bdcbb46c3abaa76924cb
    type: git
  neutron-base-plugin-networking-baremetal:
    enabled: false
  neutron-base-plugin-networking-generic-switch:
    enabled: false
  neutron-base-plugin-networking-sfc:
    enabled: false
  neutron-base-plugin-vpnaas-agent:
    enabled: false
  nova-base:
    location: https://github.com/openstack/nova.git
    reference: dee89dd3335e9bc19ac3bb6a030ee25d47233527
    type: git
  nova-base-plugin-blazar:
    enabled: false
  openstack-base:
    location: https://github.com/openstack/requirements.git
    reference: 2c8af0942819557a9176448a89620969761368fe
    type: git
  placement-base:
    location: https://github.com/openstack/placement.git
    reference: 4d3df47ee3e394e3178d58c15306620809ad2806
    type: git
  profiles:
    cinder: cinder
    heat: heat
    horizon: horizon
    main: >-
      cron,cinder,kolla-toolbox,fluentd,glance,haproxy,heat,
      horizon,keepalived,keystone,mariadb,memcached,neutron,
      nova-,placement,openvswitch,rabbitmq,rsyslog,ovn
    mariadb: mariadb
    mcrouter: mcrouter
    neutron: neutron
    nova: nova-
    toolbox: kolla-toolbox
sources:
  branch: stable/yoga
  owner: openstack
  repository:
    awx-without-k8s:
      branch: master
      kolla:
        - example-with-owner-and-branch
      owner: fitbeard
    cinder:
      kolla:
        - cinder-base
    glance:
      kolla:
        - glance-base
    heat:
      kolla:
        - heat-base
    horizon:
      kolla:
        - horizon
    keystone:
      kolla:
        - keystone-base
    neutron:
      kolla:
        - neutron-base
    nova:
      kolla:
        - nova-base
    placement:
      kolla:
        - placement-base
    requirements:
      kolla:
        - openstack-base
