---
kolla-build:
  DEFAULT:
    base: rocky
    base_image: quay.io/rockylinux/rockylinux
    base_tag: 9
    cache: true
    engine: docker
    maintainer: Tadas Sutkaitis <tadasas@gmail.com>
    namespace: fitbeard/kolla
    pull: true
    registry: quay.io
    tag: '2023.1'
  cinder-base:
    location: https://github.com/openstack/cinder.git
    reference: e848c7cfc75c549b22be2b02a9f8360f5db2b246
    type: git
  glance-base:
    location: https://github.com/openstack/glance.git
    reference: 285021bdb0ea344f995508fabb8b4e2485f2cf3c
    type: git
  heat-base:
    location: https://github.com/openstack/heat.git
    reference: 91709d22020c8cdba8fab19a00854e65bde90887
    type: git
  horizon:
    location: https://github.com/openstack/horizon.git
    reference: 068e207393455441e7bad0eb5958be6a3c35f505
    type: git
  horizon-additions-custom-theme:
    location: https://github.com/fitbeard/openstack-horizon-custom-theme.git
    reference: 8f5e111b6382b0d3d22d9fd87cb86acd1150dd7d
    type: git
  horizon-plugin-blazar-dashboard:
    enabled: false
  horizon-plugin-cloudkitty-dashboard:
    enabled: false
  horizon-plugin-designate-dashboard:
    enabled: false
  horizon-plugin-freezer-web-ui:
    enabled: false
  horizon-plugin-heat-dashboard:
    enabled: false
  horizon-plugin-ironic-ui:
    enabled: false
  horizon-plugin-magnum-ui:
    enabled: false
  horizon-plugin-manila-ui:
    enabled: false
  horizon-plugin-masakari-dashboard:
    enabled: false
  horizon-plugin-mistral-dashboard:
    enabled: false
  horizon-plugin-murano-dashboard:
    enabled: false
  horizon-plugin-neutron-vpnaas-dashboard:
    enabled: false
  horizon-plugin-octavia-dashboard:
    enabled: false
  horizon-plugin-sahara-dashboard:
    enabled: false
  horizon-plugin-senlin-dashboard:
    enabled: false
  horizon-plugin-solum-dashboard:
    enabled: false
  horizon-plugin-tacker-dashboard:
    enabled: false
  horizon-plugin-trove-dashboard:
    enabled: false
  horizon-plugin-vitrage-dashboard:
    enabled: false
  horizon-plugin-watcher-dashboard:
    enabled: false
  horizon-plugin-zun-ui:
    enabled: false
  keystone-base:
    location: https://github.com/openstack/keystone.git
    reference: 1c2d5178852155e3c6ce19352a03e9fb57c6c5f6
    type: git
  neutron-base:
    location: https://github.com/openstack/neutron.git
    reference: 331f6ae2400a1120b63f966c0e463dd4598bd2c9
    type: git
  neutron-base-plugin-networking-baremetal:
    enabled: false
  neutron-base-plugin-networking-generic-switch:
    enabled: false
  neutron-base-plugin-networking-sfc:
    enabled: false
  neutron-base-plugin-vpnaas-agent:
    enabled: false
  nova-base:
    location: https://github.com/openstack/nova.git
    reference: 4b4fc274812e4c0bbc724c45a7c7d01a4cd657dc
    type: git
  nova-base-plugin-blazar:
    enabled: false
  openstack-base:
    location: https://github.com/openstack/requirements.git
    reference: 5e480a3847e93174b46c203d10feb4f236945081
    type: git
  placement-base:
    location: https://github.com/openstack/placement.git
    reference: b3652feea1855c9481c9441976379d9851c0c62f
    type: git
  profiles:
    cinder: cinder
    heat: heat
    horizon: horizon
    main: >-
      cron,cinder,kolla-toolbox,fluentd,glance,haproxy,heat,
      horizon,keepalived,keystone,mariadb,memcached,neutron,
      nova-,placement,openvswitch,ovn,rabbitmq,rsyslog
    mariadb: mariadb
    mcrouter: mcrouter
    neutron: neutron
    nova: nova-
    toolbox: kolla-toolbox
  skyline-apiserver:
    location: https://github.com/openstack/skyline-apiserver.git
    reference: 326a503d6cece6701922a5a3ed1a980efa12e2f5
    type: git
  skyline-console:
    location: https://github.com/openstack/skyline-console.git
    reference: d4cae6dd6a96d74b754c590fd2dd48fab83a345f
    type: git
sources:
  branch: stable/2023.1
  owner: openstack
  repository:
    cinder:
      kolla:
        - cinder-base
    glance:
      kolla:
        - glance-base
    heat:
      kolla:
        - heat-base
    horizon:
      kolla:
        - horizon
    keystone:
      kolla:
        - keystone-base
    neutron:
      kolla:
        - neutron-base
    nova:
      kolla:
        - nova-base
    openstack-horizon-custom-theme:
      branch: main
      kolla:
        - horizon-additions-custom-theme
      owner: fitbeard
    placement:
      kolla:
        - placement-base
    requirements:
      kolla:
        - openstack-base
