---
name: auto-build
on:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      releases: ${{ steps.changes.outputs.changes }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create release filters
        run: |
          for release in $(ls -dl releases/** | grep "^d" | awk '{ print $9 }')
          do
            echo "$release: $release/**" >> .filters.yml
          done

      - name: Get changed releases
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: .filters.yml

  build:
    runs-on: ubuntu-latest

    needs:
      - changes

    strategy:
      matrix:
        release: ${{ fromJson(needs.changes.outputs.releases) }}

    if: ${{ needs.changes.outputs.releases != '[]' }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r ${{ matrix.release }}/requirements.txt

      - name: Generate kolla config
        run: |
          python kolla-builder.py generate-config -i ${{ matrix.release }}/config.yml -o ${{ matrix.release }}/kolla-build.conf

      - name: Build kolla images
        run: |
          kolla-build --version
